name: zstash
description: zstash cache plugin for Buildkite. Supports Linux and macOS
author: https://github.com/buildkite
requirements:
  - zstash
configuration:
  properties:
    id:
      type: string
    key:
      type: string
    fallback_keys:
      type: string
    paths:
      type: string
    bucket-url:
      type: string
    store:
      # Keep this in sync with the RestoreCmd.Store attribute
      # in https://github.com/buildkite/zstash/blob/main/internal/commands/restore.go
      enum: ["s3", "nsc"]
      default: "s3"
    registry:
      type: string
      default: "~"
    skip-save:
      type: boolean
  additionalProperties: false
