#!/usr/bin/env bash
set -Eeufo pipefail

zstash_ids="${BUILDKITE_PLUGIN_ZSTASH_IDS:-}"
zstash_config="${BUILDKITE_PLUGIN_ZSTASH_CONFIG:-}"

ZSTASH_FLAGS=""

if [ "${zstash_ids}" != "" ]; then
  ZSTASH_FLAGS="${ZSTASH_FLAGS} --ids ${zstash_ids}"
fi

if [ "${zstash_config}" != "" ]; then
  ZSTASH_FLAGS="${ZSTASH_FLAGS} --config ${zstash_config}"
fi

if [ "${ZSTASH_FLAGS}" != "" ]; then
  zstash save "${ZSTASH_FLAGS}"
else
  zstash save
fi
