#!/usr/bin/env bash
set -Eeufo pipefail

zstash_ids="${BUILDKITE_PLUGIN_ZSTASH_IDS:-}"
zstash_config="${BUILDKITE_PLUGIN_ZSTASH_CONFIG:-}"
zstash_command="zstash restore"

if [ "${zstash_ids}" != "" ]; then
  zstash_command+=" --ids ${zstash_ids}"
fi

if [ "${zstash_config}" != "" ]; then
  zstash_command+=" --config ${zstash_config}"
fi

${zstash_command} | read -r cache_result

echo "Cache HIT: ${cache_result}"
